### ISSUE TITLE
Error when running workarena-install

### ISSUE THREAD

**Issue by flbyrne** [ServiceNow/WorkArena#13] opened 2024-05-27 01:44 UTC
`(browsergym) flor@flor-VirtualBox:~$ workarena-install
Traceback (most recent call last):
  File "/home/flor/.local/bin/workarena-install", line 5, in <module>
    from browsergym.workarena.install import main
  File "/home/flor/.local/lib/python3.9/site-packages/browsergym/workarena/__init__.py", line 3, in <module>
    from browsergym.core.registration import register_task
  File "/home/flor/.local/lib/python3.9/site-packages/browsergym/core/__init__.py", line 24, in <module>
    from .registration import register_task
  File "/home/flor/.local/lib/python3.9/site-packages/browsergym/core/registration.py", line 4, in <module>
    from .env import BrowserEnv
  File "/home/flor/.local/lib/python3.9/site-packages/browsergym/core/env.py", line 13, in <module>
    from .chat import Chat
  File "/home/flor/.local/lib/python3.9/site-packages/browsergym/core/chat.py", line 14, in <module>
    CHATBOX_DIR = resources.files(chat_files)
  File "/usr/lib/python3.9/importlib/resources.py", line 147, in files
    return _common.from_package(_get_package(package))
  File "/usr/lib/python3.9/importlib/_common.py", line 14, in from_package
    return fallback_resources(package.__spec__)
  File "/usr/lib/python3.9/importlib/_common.py", line 18, in fallback_resources
    package_directory = pathlib.Path(spec.origin).parent
  File "/usr/lib/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

**Comment by gasse** [comment] 2024-05-27 17:04
Hi @flbyrne , can you please provide details about your specific config? (pip list)

**Comment by flbyrne** [comment] 2024-05-27 18:26
Hi Maxime,

I appreciate your quick response! Here is my pip list:

(browsergym) ***@***.***:~$ pip list
Package                   Version
------------------------- --------------------
aiohttp                   3.9.5
aiolimiter                1.1.0
aiosignal                 1.3.1
altair                    5.3.0
annotated-types           0.7.0
anyio                     4.3.0
apturl                    0.5.2
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
async-timeout             4.0.3
attrs                     23.2.0
Babel                     2.15.0
bcrypt                    3.1.7
beartype                  0.12.0
beautifulsoup4            4.12.3
bleach                    6.1.0
blinker                   1.8.2
Brlapi                    0.7.0
browsergym                0.3.3
browsergym-core           0.3.3
browsergym-experiments    0.3.3
browsergym-miniwob        0.3.3
browsergym-webarena       0.3.3
browsergym-workarena      0.2.1
certifi                   2019.11.28
cffi                      1.16.0
chardet                   3.0.4
charset-normalizer        3.3.2
click                     8.1.7
cloudpickle               3.0.0
colorama                  0.4.3
comm                      0.2.2
command-not-found         0.3
cryptography              2.8
cupshelpers               1.0
datasets                  2.19.1
dbus-python               1.2.16
debugpy                   1.8.1
decorator                 4.4.2
defer                     1.0.6
defusedxml                0.7.1
dill                      0.3.8
distro                    1.9.0
distro-info               0.23+ubuntu1.1
duplicity                 0.8.12.0
english-words             2.0.1
entrypoints               0.3
evaluate                  0.4.2
exceptiongroup            1.2.1
executing                 2.0.1
Faker                     25.2.0
Farama-Notifications      0.0.4
fasteners                 0.14.1
fastjsonschema            2.19.1
filelock                  3.14.0
flask                     3.0.3
fqdn                      1.5.1
frozenlist                1.4.1
fsspec                    2024.3.1
future                    0.18.2
greenlet                  3.0.0
gymnasium                 0.29.1
h11                       0.14.0
httpcore                  1.0.5
httplib2                  0.14.0
httpx                     0.27.0
huggingface-hub           0.23.1
idna                      2.8
importlib-metadata        7.1.0
ipykernel                 6.29.4
ipython                   8.18.1
ipython-genutils          0.2.0
isoduration               20.11.0
itsdangerous              2.2.0
jedi                      0.19.1
jinja2                    3.1.4
joblib                    1.4.2
json5                     0.9.25
jsonpointer               2.4
jsonschema                4.22.0
jsonschema-specifications 2023.12.1
jupyter-client            8.6.2
jupyter-core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter-server            2.14.0
jupyter-server-terminals  0.5.3
jupyterlab                4.2.1
jupyterlab-pygments       0.3.0
jupyterlab-server         2.27.2
keyring                   18.0.1
language-selector         0.1
launchpadlib              1.10.13
lazr.restfulclient        0.14.2
lazr.uri                  1.0.3
libwebarena               0.0.3
lockfile                  0.12.2
louis                     3.12.0
lxml                      5.2.2
macaroonbakery            1.3.1
Mako                      1.1.0
MarkupSafe                2.1.5
matplotlib-inline         0.1.7
mistune                   3.0.2
monotonic                 1.5
multidict                 6.0.5
multiprocess              0.70.16
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nest-asyncio              1.6.0
netifaces                 0.10.4
nltk                      3.8.1
notebook                  7.2.0
notebook-shim             0.2.4
numpy                     1.26.4
oauthlib                  3.1.0
olefile                   0.46
openai                    1.30.3
overrides                 7.7.0
packaging                 24.0
pandas                    2.2.2
pandocfilters             1.5.1
paramiko                  2.6.0
parso                     0.8.4
pexpect                   4.6.0
pillow                    10.3.0
pip                       20.0.2
platformdirs              4.2.2
playwright                1.39.0
prometheus-client         0.20.0
prompt-toolkit            3.0.43
protobuf                  3.6.1
psutil                    5.9.8
ptyprocess                0.7.0
pure-eval                 0.2.2
pyarrow                   16.1.0
pyarrow-hotfix            0.6
pycairo                   1.16.2
pycparser                 2.22
pycups                    1.9.73
pydantic                  2.7.1
pydantic-core             2.18.2
pyee                      11.0.1
pygments                  2.18.0
PyGObject                 3.36.0
PyJWT                     1.7.1
pymacaroons               0.13.0
PyNaCl                    1.3.0
pyparsing                 3.1.2
pyRFC3339                 1.1
python-apt                2.0.1+ubuntu0.20.4.1
python-dateutil           2.8.2
python-debian             0.1.36+ubuntu1.1
python-json-logger        2.0.7
pytz                      2024.1
pyxdg                     0.26
PyYAML                    5.3.1
pyzmq                     26.0.3
referencing               0.35.1
regex                     2024.5.15
reportlab                 3.5.34
requests                  2.32.2
requests-unixsocket       0.2.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.18.1
safetensors               0.4.3
SecretStorage             2.3.1
Send2Trash                1.8.3
setuptools                45.2.0
simplejson                3.16.0
six                       1.14.0
sniffio                   1.3.1
soupsieve                 2.5
stack-data                0.6.3
systemd-python            234
tenacity                  8.3.0
terminado                 0.18.1
text-generation           0.7.0
tiktoken                  0.7.0
tinycss2                  1.3.0
tokenizers                0.19.1
tomli                     2.0.1
toolz                     0.12.1
tornado                   6.4
tqdm                      4.66.4
traitlets                 5.14.3
transformers              4.41.1
types-python-dateutil     2.9.0.20240316
types-tqdm                4.66.0.20240417
typing-extensions         4.12.0
tzdata                    2024.1
ubuntu-drivers-common     0.0.0
ubuntu-pro-client         8001
ufw                       0.36
unattended-upgrades       0.1
uri-template              1.3.0
urllib3                   1.25.8
usb-creator               0.3.7
wadllib                   1.3.3
wcwidth                   0.2.13
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.8.0
werkzeug                  3.0.3
wheel                     0.34.2
xkit                      0.0.0
xxhash                    3.4.1
yarl                      1.9.4
zipp                      3.19.0

**Comment by gasse** [comment] 2024-05-30 14:49
Hi @flbyrne , it turns out the problem is the python version. We were able to replicate the error with python=3.9, but with python=3.10 it works.

Can you update your version of Python and tell us if it works? Meanwhile we will update the requirements to python>= 3.10 in the package specifications.

**Comment by flbyrne** [comment] 2024-05-30 16:04
I started by installing browsergym and webarena. I ran into problems with
those and I was able to fix them by downgrading to 3.9. You may want to
review all of them to make sure they all have the same python version.

Flor

**Comment by aldro61** [comment] 2024-06-12 16:51
Thank you for pointing this out. Will close the issue, but we are on it.

**Closed by aldro61** 2024-06-12 16:51 UTC
Labels: Public Issue

**Comment by aldro61** [comment] 2024-10-24 15:43
Hi @flbyrne! Our data center team has identified an issue that might be causing some developer instances to be unhealthy. I think this is what was causing your issue.

**Diagnostic:** Navigate to YOUR_INSTANCE_URL/stats.do and check if the Connected to cluster node value contains ord. If it does, the node is affected by the current issue.

**Solution:** Unfortunately, the only way to get a healthy instance right now is to release your current instance and request a new one until it lives on a healthy cluster node. Now that the issue has been identified, I'm confident our data center team will resolve it quickly.

Hope this helps!

**Comment by flbyrne** [comment] 2024-10-24 16:48
I'll get a new instance then. Thank you!
